# Generated by Django 2.2.6 on 2019-10-26 01:02

import charIndex.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(max_length=200)),
                ('char_img', models.ImageField(null=True, upload_to=charIndex.models.Character.get_image_path)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(max_length=200)),
                ('movement_speed', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=0)),
                ('range', models.IntegerField(default=0)),
                ('bullets_per_attack', models.IntegerField(default=0)),
                ('dps', models.IntegerField(default=0)),
                ('super_range', models.IntegerField(default=0)),
                ('bullets_per_super', models.IntegerField(default=0)),
                ('super_dps', models.IntegerField(default=0)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='charIndex.Character')),
            ],
        ),
    ]
