# Generated by Django 2.2.6 on 2019-10-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charIndex', '0003_auto_20191025_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='reload_speed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
