# Generated by Django 2.2.6 on 2019-10-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charIndex', '0004_stats_reload_speed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='dps',
            new_name='damage_per_bullet',
        ),
        migrations.AlterField(
            model_name='character',
            name='char_name',
            field=models.CharField(max_length=200, verbose_name='character name'),
        ),
        migrations.AlterField(
            model_name='character',
            name='char_origin',
            field=models.CharField(max_length=200, verbose_name='character origin'),
        ),
        migrations.AlterField(
            model_name='character',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date created'),
        ),
    ]
