# Generated by Django 2.2.6 on 2019-10-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charIndex', '0006_auto_20191025_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='bullets_per_attack',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='bullets_per_super',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='damage_per_bullet',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='health',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='movement_speed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='range',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='reload_speed',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='super_dps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='super_range',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
