# Generated by Django 2.2.6 on 2019-10-26 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charIndex', '0007_auto_20191025_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='id',
        ),
        migrations.AlterField(
            model_name='stats',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='charIndex.Character'),
        ),
    ]
