# Generated by Django 2.2.6 on 2019-10-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charIndex', '0008_auto_20191025_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='super_dps',
        ),
        migrations.AddField(
            model_name='stats',
            name='super_damage_per_bullet',
            field=models.IntegerField(null=True, verbose_name='Super damage per bullet'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='bullets_per_attack',
            field=models.IntegerField(null=True, verbose_name='Bullets per attack'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='bullets_per_super',
            field=models.IntegerField(null=True, verbose_name='Bullets per super'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='damage_per_bullet',
            field=models.IntegerField(null=True, verbose_name='Damage per bullet'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='health',
            field=models.IntegerField(null=True, verbose_name='Health'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='movement_speed',
            field=models.IntegerField(null=True, verbose_name='Movement speed'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='range',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Range'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='rarity',
            field=models.CharField(max_length=200, verbose_name='Rarity'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='reload_speed',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Reload speed'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='super_range',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Super range'),
        ),
    ]
